// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADrVVBSntxrePYIYcDs31wS6FQ-anTkLk',
    appId: '1:487970241362:web:3c315ce965518104f6588b',
    messagingSenderId: '487970241362',
    projectId: 'reminders-app-7d258',
    authDomain: 'reminders-app-7d258.firebaseapp.com',
    storageBucket: 'reminders-app-7d258.appspot.com',
    measurementId: 'G-VPEHW2Q61H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0kxF1sEQ1m5-Dbe-LBw5ib5oxIszOL58',
    appId: '1:487970241362:android:39c363467e375bd2f6588b',
    messagingSenderId: '487970241362',
    projectId: 'reminders-app-7d258',
    storageBucket: 'reminders-app-7d258.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwXTwSxdxjQE4-Va-aZ84cnDT7AekTTyE',
    appId: '1:487970241362:ios:76c405b7ca09fe66f6588b',
    messagingSenderId: '487970241362',
    projectId: 'reminders-app-7d258',
    storageBucket: 'reminders-app-7d258.appspot.com',
    iosClientId: '487970241362-j3e8joriga696sjoc0ohj02chn4p5a48.apps.googleusercontent.com',
    iosBundleId: 'com.reminders.app',
  );
}
